<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="div container">
    <div class="jumbotron">
        <h1 class="display-4">Bem Vindo ao Site</h1>
        <p class="lead">Projeto Catalogo de Produtos em PHP e MVC</p>

        <a class="btn btn-primary btn-lg" href="https://github.com/JulioPaschoal" role="button">Learn more</a>
    </div>
    <div class="row">
        <?php foreach($this->products as $product):?>
            <div class="col-md-4">
                <img src="http://via.placeholder.com/350x150?text=<?=$product['name'];?>" alt="" class="img-responsive">
                <h2><a href="<?=HOME;?>/product/<?=$product['id'];?>"><?=$product['name'];?></a></h2>
                <p><?=$product['description'];?></p>
                <p>R$ <?=number_format($product['price'], 2, ',', '.');?></p>
            </div>
        <?php endforeach;?>
    </div>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>

